# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args merge from entity @s data.locators.chair_loc
function animated_java:eva/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.floor
function animated_java:eva/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args