# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
summon minecraft:item_display ^0 ^42.0012827327 ^-1.5507648433 {Tags:["aj.eva.bone.chair.child","aj.eva.bone.chair.child.locator","aj.eva.bone.chair.decendant","aj.eva.bone.chair.decendant.locator","aj.eva.bone.chair.tree","aj.eva.bone.chest.decendant","aj.eva.bone.chest.decendant.locator","aj.eva.bone.chest.tree","aj.eva.bone.entry_plug.decendant","aj.eva.bone.entry_plug.decendant.locator","aj.eva.bone.entry_plug.tree","aj.eva.bone.eva.decendant","aj.eva.bone.eva.decendant.locator","aj.eva.bone.eva.tree","aj.eva.entity","aj.eva.locator","aj.eva.locator.chair_loc","aj.eva.node","aj.eva.node.chair_loc","aj.global.bone.chair.child","aj.global.bone.chair.child.locator","aj.global.bone.chair.decendant","aj.global.bone.chair.decendant.locator","aj.global.bone.chair.tree","aj.global.bone.chest.decendant","aj.global.bone.chest.decendant.locator","aj.global.bone.chest.tree","aj.global.bone.entry_plug.decendant","aj.global.bone.entry_plug.decendant.locator","aj.global.bone.entry_plug.tree","aj.global.bone.eva.decendant","aj.global.bone.eva.decendant.locator","aj.global.bone.eva.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.chair_loc","aj.new"]}
execute as @n[ type=minecraft:item_display, tag=aj.eva.locator.chair_loc, tag=aj.new, distance=..52 ] run function animated_java:eva/zzz/summon/as_data_entity/as_locator/chair_loc
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_chair_loc set from storage animated_java:gu out
data modify entity @s data.locators.chair_loc.uuid set from storage animated_java:gu out
summon minecraft:item_display ^0 ^0.2874793368 ^0.3445172467 {Tags:["aj.eva.bone.eva.decendant","aj.eva.bone.eva.decendant.locator","aj.eva.bone.eva.tree","aj.eva.bone.floor1.child","aj.eva.bone.floor1.child.locator","aj.eva.bone.floor1.decendant","aj.eva.bone.floor1.decendant.locator","aj.eva.bone.floor1.tree","aj.eva.entity","aj.eva.locator","aj.eva.locator.floor","aj.eva.node","aj.eva.node.floor","aj.global.bone.eva.decendant","aj.global.bone.eva.decendant.locator","aj.global.bone.eva.tree","aj.global.bone.floor1.child","aj.global.bone.floor1.child.locator","aj.global.bone.floor1.decendant","aj.global.bone.floor1.decendant.locator","aj.global.bone.floor1.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.floor","aj.new"]}
execute as @n[ type=minecraft:item_display, tag=aj.eva.locator.floor, tag=aj.new, distance=..18 ] run function animated_java:eva/zzz/summon/as_data_entity/as_locator/floor
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_floor set from storage animated_java:gu out
data modify entity @s data.locators.floor.uuid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.mainhand] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_mainhand set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.right_forearm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_forearm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.right_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.right_wing] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_wing set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.storage] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_storage set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.offhand] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_offhand set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.left_forearm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_forearm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.left_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.left_wing] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_wing set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.door] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_door set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.movable] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_movable set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.chair] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_chair set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.entry_plug] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_entry_plug set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.jaw] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_jaw set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.top_op] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_top_op set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.bottom_op] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bottom_op set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.chest] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_chest set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.right_foot] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_foot set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.right_calf] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_calf set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.right_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.left_foot] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_foot set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.left_calf] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_calf set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.left_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.torso] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_torso set from storage animated_java:gu out