# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:eva/animations/backwards/zzz/apply_frame {frame: 56}
scoreboard players add @s aj.backwards.frame 1