# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:eva/root/on_tick/select_locator_chair_loc with entity @s data.locators.chair_loc
function animated_java:eva/root/on_tick/select_locator_floor with entity @s data.locators.floor