# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^0.2874793368 ^0.3445172467 ~0 ~-53.3
data modify entity @s data.locators.floor merge value { px: 0, py: 0.2874793368, pz: 0.3445172467, ry: 0, rx: -53.3 }