# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^42.0012827327 ^-1.5507648433 ~0 ~-30
data modify entity @s data.locators.chair_loc merge value { px: 0, py: 42.0012827327, pz: -1.5507648433, ry: 0, rx: -30 }