# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:eva/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b3167a2630f590da1867582c76d663a0572668921d09b9e8aca73468748d2d4a'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack