# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.fall.frame matches 41.. run scoreboard players set @s aj.fall.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.fall.frame
execute at @s run function animated_java:eva/animations/fall/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.fall.frame 1