# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:eva/animations/pause_all
tag @s add aj.eva.animation.fall.playing
scoreboard players set @s aj.fall.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:eva/animations/fall/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only