# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.idleold.frame
scoreboard objectives remove aj.walkold.frame
scoreboard objectives remove aj.backwardsold.frame
scoreboard objectives remove aj.openold.frame
scoreboard objectives remove aj.closeold.frame
scoreboard objectives remove aj.runold.frame
scoreboard objectives remove aj.jumpold.frame
scoreboard objectives remove aj.fallold.frame
scoreboard objectives remove aj.aimold.frame
scoreboard objectives remove aj.walk_gunold.frame
scoreboard objectives remove aj.pre_punchold.frame
scoreboard objectives remove aj.punchold.frame
scoreboard objectives remove aj.eva_walk_w2old.frame
scoreboard objectives remove aj.eva_walk_newold.frame
scoreboard objectives remove aj.idle.frame
scoreboard objectives remove aj.walk.frame
scoreboard objectives remove aj.backwards.frame
scoreboard objectives remove aj.run.frame
scoreboard objectives remove aj.fast_jump.frame
scoreboard objectives remove aj.open.frame
scoreboard objectives remove aj.close.frame
scoreboard objectives remove aj.jump.frame
scoreboard objectives remove aj.fall.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:eva)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'eva'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']