# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:eva/animations/pause_all
tag @s add aj.eva.animation.fast_jump.playing
scoreboard players set @s aj.fast_jump.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:eva/animations/fast_jump/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only